import { State } from './state';



export const STATES: State[] = [

{ id: 0, name: "Alabama" },
{ id: 1, name: "Alaska" },
{ id: 2, name: "American Samoa" },
{ id: 3, name: "Arizona" },
{ id: 4, name: "Arkansas" },
{ id: 5, name: "California" },
{ id: 6, name: "Colorado" },
{ id: 7, name: "Connecticut" },
{ id: 8, name: "Delaware" },
{ id: 9, name: "District of Columbia" },
{ id: 10, name: "Florida" },
{ id: 11, name: "Georgia" },
{ id: 12, name: "Guam" },
{ id: 13, name: "Hawaii" },
{ id: 14, name: "Idaho" },
{ id: 15, name: "Illinois" },
{ id: 16, name: "Indiana" },
{ id: 17, name: "Iowa" },
{ id: 18, name: "Kansas" },
{ id: 19, name: "Kentucky" },
{ id: 20, name: "Louisiana" },
{ id: 21, name: "Maine" },
{ id: 22, name: "Maryland" },
{ id: 23, name: "Massachusetts" },
{ id: 24, name: "Michigan" },
{ id: 25, name: "Minnesota" },
{ id: 26, name: "Mississippi" },
{ id: 27, name: "Missouri" },
{ id: 28, name: "Montana" },
{ id: 29, name: "Nebraska" },
{ id: 30, name: "Nevada" },
{ id: 31, name: "New Hampshire" },
{ id: 32, name: "New Jersey" },
{ id: 33, name: "New Mexico" },
{ id: 34, name: "New York" },
{ id: 35, name: "North Carolina" },
{ id: 36, name: "North Dakota" },
{ id: 37, name: "Northern Marianas Islands" },
{ id: 38, name: "Ohio" },
{ id: 39, name: "Oklahoma" },
{ id: 40, name: "Oregon" },
{ id: 41, name: "Pennsylvania" },
{ id: 42, name: "Puerto Rico" },
{ id: 43, name: "Rhode Island" },
{ id: 44, name: "South Carolina" },
{ id: 45, name: "South Dakota" },
{ id: 46, name: "Tennessee" },
{ id: 47, name: "Texas" },
{ id: 48, name: "Utah" },
{ id: 49, name: "Vermont" },
{ id: 50, name: "Virginia" },
{ id: 51, name: "Virgin Islands" },
{ id: 52, name: "Washington" },
{ id: 53, name: "West Virginia" },
{ id: 54, name: "Wisconsin" },
{ id: 55, name: "Wyoming" }
]; 
